[package]
name = "cizrna"
authors = ["Marek Such√°nek <msuchane@redhat.com>"]
version = "0.10.1"
edition = "2021"
# Check the Rust version using `cargo msrv verify`.
rust-version = "1.57"
description = "Generate an AsciiDoc release notes document from tracking tickets."
license = "GPL-3.0-or-later"
readme = "README.md"
categories = ["command-line-utilities", "text-processing", "template-engine"]
keywords = ["release notes", "asciidoc", "documentation", "Red Hat"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["cargo"] }
log = "0.4"
simplelog = "0.12"
# Disable support for tracing_error and SpanTrace in eyre
color-eyre = { version = "0.6", default-features = false }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "1.0"
serde_yaml = "0.8"
bugzilla_query = "^0.9"
jira_query = "^0.7"
tokio = { version = "^1", features = ["full"] }
askama = "^0.11"
chrono = "^0.4"
counter = "^0.5"
regex = "1.5"

[package.metadata.rpm]
package = "cizrna"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
cizrna = { path = "/usr/bin/cizrna" }
